CREATE OR REPLACE TABLE `Person` (
	`ID` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Vorname` VARCHAR(255) NOT NULL,
	`Nachname` VARCHAR(255) NOT NULL,
	`Geburtsdatum` DATE NOT NULL,
	`Rolle` INTEGER NOT NULL,
	PRIMARY KEY(`ID`)
);

CREATE UNIQUE INDEX `Person_index_0`
ON `Person` (`PersonenID`);
CREATE OR REPLACE TABLE `Boat` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Typ` TINYINT NOT NULL,
	`Status` INTEGER NOT NULL,
	`Große` VARCHAR(255) NOT NULL,
	`Liegeplatz` INTEGER NOT NULL UNIQUE,
	PRIMARY KEY(`id`)
);

CREATE OR REPLACE TABLE `Liegeplatz` (
	`ID` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Position` TEXT(65535),
	PRIMARY KEY(`ID`)
);

CREATE OR REPLACE TABLE `Boat-Reservation` (
	`ID` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`User_FID` INTEGER NOT NULL,
	`Start-Date` DATE NOT NULL,
	`End-Date` DATE NOT NULL,
	`Boat_FID` INTEGER NOT NULL,
	PRIMARY KEY(`ID`)
);

CREATE OR REPLACE TABLE `Liegeplatz-Reservation` (
	`ID` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Start-Date` DATE NOT NULL,
	`End-Date` DATE NOT NULL,
	`Liegeplatz_FID` INTEGER NOT NULL,
	`User_FID` INTEGER NOT NULL,
	PRIMARY KEY(`ID`)
);

ALTER TABLE `Liegeplatz`
ADD FOREIGN KEY(`ID`) REFERENCES `Boat`(`Liegeplatz`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Boat-Reservation`
ADD FOREIGN KEY(`Boat_FID`) REFERENCES `Boat`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Boat-Reservation`
ADD FOREIGN KEY(`User_FID`) REFERENCES `Person`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Liegeplatz-Reservation`
ADD FOREIGN KEY(`Liegeplatz_FID`) REFERENCES `Liegeplatz`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Liegeplatz-Reservation`
ADD FOREIGN KEY(`User_FID`) REFERENCES `Person`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;