CREATE OR REPLACE TABLE `Person` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
    `Vorname` VARCHAR(255) NOT NULL,
    `Nachname` VARCHAR(255) NOT NULL,
    `Geburtsdatum` DATE NOT NULL,
    `Rolle` INTEGER NOT NULL,
    PRIMARY KEY(`ID`)
);

CREATE OR REPLACE TABLE `Liegeplatz` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
    `Position` TEXT,
    PRIMARY KEY(`ID`)
);

CREATE OR REPLACE TABLE `Boat` (
    `id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
    `Typ` TINYINT NOT NULL,
    `Status` INTEGER NOT NULL,
    `Groesse` VARCHAR(255) NOT NULL,
    `Liegeplatz` INTEGER NOT NULL,
    PRIMARY KEY(`id`),
    FOREIGN KEY(`Liegeplatz`) REFERENCES `Liegeplatz`(`ID`)
        ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE OR REPLACE TABLE `Boat_Reservation` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
    `User_FID` INTEGER NOT NULL,
    `Start_Date` DATE NOT NULL,
    `End_Date` DATE NOT NULL,
    `Boat_FID` INTEGER NOT NULL,
    PRIMARY KEY(`ID`),
    FOREIGN KEY(`Boat_FID`) REFERENCES `Boat`(`id`)
        ON UPDATE NO ACTION ON DELETE NO ACTION,
    FOREIGN KEY(`User_FID`) REFERENCES `Person`(`ID`)
        ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE OR REPLACE TABLE `Liegeplatz_Reservation` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
    `Start_Date` DATE NOT NULL,
    `End_Date` DATE NOT NULL,
    `Liegeplatz_FID` INTEGER NOT NULL,
    `User_FID` INTEGER NOT NULL,
    PRIMARY KEY(`ID`),
    FOREIGN KEY(`Liegeplatz_FID`) REFERENCES `Liegeplatz`(`ID`)
        ON UPDATE NO ACTION ON DELETE NO ACTION,
    FOREIGN KEY(`User_FID`) REFERENCES `Person`(`ID`)
        ON UPDATE NO ACTION ON DELETE NO ACTION
);
